train: /Users/lorenaderezanin/PycharmProjects/WhatIsPants/deepfash/train
val: /Users/lorenaderezanin/PycharmProjects/WhatIsPants/deepfash/val

# number of classes
nc: 1

# class names
names:
 0: This is pants
